### PR TITLE
lock screen test

### PR DESCRIPTION
**Pull request by jallee**

### CODE REVIEW

**Comment by frank210** [comment]
Yo man. I'm still at work not gonna make it to class. Let me know if there's anything you want to do for the app.

**Comment by jallee** [comment]
No problem midterm next week

**Comment by jallee** [comment]
hey I don't know if you got the chance to look at the changes I was trying
to make to the app But I'm having trouble getting the app to return to the
main page after sending it to the account settings page and I'm sure I ve
got that part wrong some how do you mind taking a look at it when you get
some time

**Comment by frank815** [comment]
I'll take a look at tonight see what's up.

**Comment by frank815** [comment]
Finally got a chance to look at the app. It's the background image your
using. try changing it to a more simple one or smaller one. it's crashing
the app when the it tries to redraw the screen.

not sure if you figured it out already.

**Pull request merged**
